apiVersion: v1
kind: Pod
metadata:
  name: node-api-crashing
  namespace: team-app1
spec:
  containers:
    - name: node-backend
      image: node:18
      command: ["sh", "-c"]
      args:
        - |
          echo "Starting backend...";
          node -e "throw new Error('Database connection failed: timeout');"
